---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Concado.
--- DateTime: 05.10.2021 09:27
---

local ESX = nil
local menuOpen = false
local menuInitialized = false

local craftingInProgress = false
local craftingCanceled = false
local craftDuration = 0
local elapsedTime = 0

local ped = nil

-- Get ESX Object
Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        ped = PlayerPedId()
        Citizen.Wait(1)
    end
end)

RegisterRawNuiCallback('closeMenu', function()
    menuOpen = false
    toggleGui(false)
end)

local function toggleGui(state)
    SetNuiFocus(state, state)
    if not menuInitialized then
        SendNUIMessage({
            type = 'setTitle',
            title = Config.MenuTitle
        })
        menuInitialized = true
    end

    SendNUIMessage({
        type = 'enableui',
        enable = state,
        isCrafting = craftingInProgress,
        categories = Config.Categories,
        recipes = prepareRecipes(Config.Recipes)
    })
end


-- This sets the amount of items the player has
local function prepareRecipes(data)
    local playerInventory = ESX.GetPlayerData().inventory

    for key, value in pairs(data) do
        for keyi, valuei in pairs(data[key]) do
            local item = playerInventory[data[key].Ingredients[keyi].Identifier]
            if not item == nil then
                data[key].Ingredients[keyi].Has = 0
            else
                data[key].Ingredients[keyi].Has = item.count
            end
        end
    end

    return data
end