---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Concado.
--- DateTime: 05.10.2021 09:35
---

--Recipe Template
--[[
    {
        Name = "Test",
        Identifier = "test",
        Category = "Kleidung", -- This has to be a category which was defined above
        Description = 'This is a test recipe',
        DefaultImage = '',
        CraftDuration = 15, -- The Time it takes to craft this item
        CraftAmount = 1, -- The amount of items you get from crafting
        Ingredients = { -- Crafting requirements
            {
                Name = "Test Ingredient",
                Identifier = "test_ingred", -- has to be the item name in the database
                Icon = "far fa-cut",
                Amount = 5 -- The amount you need rom this item
            },
            {
                Name = "Test Ingredient 2",
                Identifier = "test_ingred2", -- has to be the item name in the database
                Icon = "far fa-cut",
                Amount = 1 -- The amount you need rom this item
            }
        }
    }
--]]

-- Icons can be choosen from here https://fontawesome.com/v5.15/icons?d=gallery&p=2

Config = {}
Config.MenuTitle = "Concado's Crafting Menu"
Config.MenuOpenKey = 38
Config.MaxDistanceFromTable = 3

-- if true it takes a picture out of the specified folder, the name has to be RecipeIdentifier.png
Config.UseImageFolder = false
Config.ImageFolder = 'https://resourcename/folder'

Config.Tables = {
    ['1'] = { x = 1691.17, y = 3588.65, z = 35.62 }
}

Config.Categories = {
    { Name = "Kleidung", Icon = "far fa-tshirt" },
    { Name = 'Waffen', Icon = "far fa-raygun" }
}

Config.Recipes = {
    {
        Name = "Pullover",
        Identifier = "pullover",
        Category = "Kleidung", -- This has to be a category which was defined above
        Description = 'This is a test recipe',
        DefaultImage = 'https://awgikyrvip.cloudimg.io/v7/_media_/media/image/1d/6a/47/_FrontImage_30403tyZaMF8ZT5TVg.png',
        CraftDuration = 15, -- The Time it takes to craft this item
        CraftAmount = 1, -- The amount of items you get from crafting
        Ingredients = { -- Crafting requirements
            {
                Name = "Wolle",
                Identifier = "wool", -- has to be the item name in the database
                Icon = "far fa-cut",
                Amount = 5 -- The amount you need rom this item
            }
        }
    }
}