---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Concado.
--- DateTime: 05.10.2021 09:35
---

--Recipe Template
--[[
    {
        Name = "Test",
        Identifier = "test",
        Category = "Kleidung", -- This has to be a category which was defined above
        Description = 'This is a test recipe',
        DefaultImage = '',
        CraftDuration = 15, -- The Time it takes to craft this item
        CraftAmount = 1, -- The amount of items you get from crafting
        Ingredients = { -- Crafting requirements
            {
                Name = "Test Ingredient",
                Identifier = "test_ingred", -- has to be the item name in the database
                Icon = "far fa-cut",
                Amount = 5 -- The amount you need rom this item
            },
            {
                Name = "Test Ingredient 2",
                Identifier = "test_ingred2", -- has to be the item name in the database
                Icon = "far fa-cut",
                Amount = 1 -- The amount you need rom this item
            }
        }
    }
--]]

Config = {}
Config.MenuTitle = "Concado's Crafting Menu"
Config.MenuOpenKey = 38
Config.MaxDistanceFromTable = 3

Config.UseImageFolder = true
Config.ImageFolder = 'https://resourcename/folder'

Config.Tables = {
    ['1'] = { x = 1691.17, y = 3588.65, z = 35.62 }
}

Config.Categories = {
    { Name = "Kleidung", Icon = "" },
    { Name = 'Waffen', Icon = "" }
}

Config.Recipes = {
    {
        Name = "Pullover",
        Identifier = "pullover",
        Category = "Kleidung", -- This has to be a category which was defined above
        Description = 'This is a test recipe',
        DefaultImage = '',
        CraftDuration = 15, -- The Time it takes to craft this item
        CraftAmount = 1, -- The amount of items you get from crafting
        Ingredients = { -- Crafting requirements
            {
                Name = "Wolle",
                Identifier = "wool", -- has to be the item name in the database
                Icon = "far fa-cut",
                Amount = 5 -- The amount you need rom this item
            }
        }
    }
}