---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Elias Zech.
--- DateTime: 26.09.2021 20:39
---

fx_version 'cerulean'
games { 'gta5' }

author 'Elias Zech <elias.zech@outlook.com>'
description 'A crafting system to craft items'
version '1.0.0'

-- What to run
client_scripts {
    'client_script.js'
}
server_script 'server_script.js'

files {
    'menu/menu.html',
    'menu/js/jquery.min.js',
    'menu/js/jquery.blockUi.js',
    'menu/js/scripts.js',
    'config.json'
}
ui_page 'menu/menu.html'


