---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Concado.
--- DateTime: 05.10.2021 17:45
---

local ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

RegisterServerEvent('con:craftItem')
AddEventHandler('con:craftItem', function(blueprint, amount)
    local player = ESX.GetPlayerFromId(source)
    ProcessBlueprint(player, blueprint, amount)
end)

function ProcessBlueprint(player, blueprint, amount)
    for key, ingredient in pairs(blueprint.Ingredients) do
        player.removeInventoryItem(ingredient.Identifier, ingredient.Amount)
    end
    player.addInventoryItem(blueprint.Identifier, blueprint.CraftAmount * amount)
end